<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../PXA.Migration.Spreadsheet.Code.Aspose/PXA.Migration.Spreadsheet.Code.Aspose.csproj" />
    <ProjectReference Include="../PXA.Migration.Spreadsheet.Code.ClosedXml/PXA.Migration.Spreadsheet.Code.ClosedXml.csproj" />
    <ProjectReference Include="../PXA.Migration.Spreadsheet.Code.Epplus/PXA.Migration.Spreadsheet.Code.Epplus.csproj" />
    <ProjectReference Include="../PXA.Migration.Spreadsheet.Code.GemBox/PXA.Migration.Spreadsheet.Code.GemBox.csproj" />
    <ProjectReference Include="../PXA.Migration.Spreadsheet.Code.Npoi/PXA.Migration.Spreadsheet.Code.Npoi.csproj" />
    <ProjectReference Include="../PXA.Migration.Spreadsheet.Code.Spire/PXA.Migration.Spreadsheet.Code.Spire.csproj" />
    <ProjectReference Include="../PXA.Migration.Spreadsheet.Code.SpreadsheetLight/PXA.Migration.Spreadsheet.Code.SpreadsheetLight.csproj" />
    <ProjectReference Include="../PXA.Migration.Spreadsheet.Code.Syncfusion/PXA.Migration.Spreadsheet.Code.Syncfusion.csproj" />
    <ProjectReference Include="../PXA.Migration.Abstractions/PXA.Migration.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
