<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../PXA.Migration.AsposeCells/PXA.Migration.AsposeCells.csproj" />
    <ProjectReference Include="../PXA.Migration.ClosedXmlSpreadsheet/PXA.Migration.ClosedXmlSpreadsheet.csproj" />
    <ProjectReference Include="../PXA.Migration.EpplusSpreadsheet/PXA.Migration.EpplusSpreadsheet.csproj" />
    <ProjectReference Include="../PXA.Migration.GemBoxSpreadsheet/PXA.Migration.GemBoxSpreadsheet.csproj" />
    <ProjectReference Include="../PXA.Migration.Npoi/PXA.Migration.Npoi.csproj" />
    <ProjectReference Include="../PXA.Migration.SpireXls/PXA.Migration.SpireXls.csproj" />
    <ProjectReference Include="../PXA.Migration.SpreadsheetLight/PXA.Migration.SpreadsheetLight.csproj" />
    <ProjectReference Include="../PXA.Migration.SyncfusionXlsIo/PXA.Migration.SyncfusionXlsIo.csproj" />
    <ProjectReference Include="../PXA.Migration.Abstractions/PXA.Migration.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
