<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Canvas.Migration.AsposeCells/Canvas.Migration.AsposeCells.csproj" />
    <ProjectReference Include="../Canvas.Migration.ClosedXmlSpreadsheet/Canvas.Migration.ClosedXmlSpreadsheet.csproj" />
    <ProjectReference Include="../Canvas.Migration.EpplusSpreadsheet/Canvas.Migration.EpplusSpreadsheet.csproj" />
    <ProjectReference Include="../Canvas.Migration.GemBoxSpreadsheet/Canvas.Migration.GemBoxSpreadsheet.csproj" />
    <ProjectReference Include="../Canvas.Migration.Npoi/Canvas.Migration.Npoi.csproj" />
    <ProjectReference Include="../Canvas.Migration.SpireXls/Canvas.Migration.SpireXls.csproj" />
    <ProjectReference Include="../Canvas.Migration.SpreadsheetLight/Canvas.Migration.SpreadsheetLight.csproj" />
    <ProjectReference Include="../Canvas.Migration.SyncfusionXlsIo/Canvas.Migration.SyncfusionXlsIo.csproj" />
    <ProjectReference Include="../PXA.Migration.Abstractions/PXA.Migration.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
