auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache

ingester:
  chunk_idle_period: 10s
  max_chunk_age: 72h
  chunk_retain_period: 0s
  wal:
    enabled: false

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10s
  retention_enabled: true
  retention_delete_delay: 1s
  retention_delete_worker_count: 10
  delete_request_store: filesystem

limits_config:
  allow_structured_metadata: true
  reject_old_samples: false
  retention_period: ${PXA_TEST_LOG_RETENTION}
