<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Canvas.FileImporter.Abstractions/Canvas.FileImporter.Abstractions.csproj" />
    <ProjectReference Include="../Canvas.Core/Canvas.Core.csproj" />
    <ProjectReference Include="../Canvas.Importer/Canvas.Importer.csproj" />
  </ItemGroup>

</Project>
