<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../PXA.Migration.ActiveReportsJs/PXA.Migration.ActiveReportsJs.csproj" />
    <ProjectReference Include="../PXA.Migration.DevExpressReport/PXA.Migration.DevExpressReport.csproj" />
    <ProjectReference Include="../PXA.Migration.FastReport/PXA.Migration.FastReport.csproj" />
    <ProjectReference Include="../PXA.Migration.JasperReports/PXA.Migration.JasperReports.csproj" />
    <ProjectReference Include="../PXA.Migration.Rdl/PXA.Migration.Rdl.csproj" />
    <ProjectReference Include="../PXA.Migration.Rpx/PXA.Migration.Rpx.csproj" />
    <ProjectReference Include="../PXA.Migration.Stimulsoft/PXA.Migration.Stimulsoft.csproj" />
    <ProjectReference Include="../PXA.Migration.Telerik/PXA.Migration.Telerik.csproj" />
    <ProjectReference Include="../PXA.Core/PXA.Core.csproj" />
    <ProjectReference Include="../PXA.Migration.Abstractions/PXA.Migration.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
