<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../Canvas.Core/Canvas.Core.csproj" />
    <ProjectReference Include="../Canvas.Migration.DevExpressReport/Canvas.Migration.DevExpressReport.csproj" />
    <ProjectReference Include="../Canvas.Migration.Rdl/Canvas.Migration.Rdl.csproj" />
    <ProjectReference Include="../Canvas.Migration.Rpx/Canvas.Migration.Rpx.csproj" />
    <ProjectReference Include="../PXA.Migration.Abstractions/PXA.Migration.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
