<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="PXA.Core.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/PXA.Application/PXA.Application.csproj" />
    <ProjectReference Include="../../src/PXA.Core/PXA.Core.csproj" />
    <ProjectReference Include="../../src/PXA.Infrastructure.Converters/PXA.Infrastructure.Converters.csproj" />
    <ProjectReference Include="../../src/PXA.Infrastructure.Word/PXA.Infrastructure.Word.csproj" />
    <ProjectReference Include="../../src/PXA.Infrastructure.Spreadsheet/PXA.Infrastructure.Spreadsheet.csproj" />
    <ProjectReference Include="../../src/PXA.Infrastructure.Pdf/PXA.Infrastructure.Pdf.csproj" />
    <ProjectReference Include="../../PXA.WebApi/PXA.WebApi.csproj" />
    <ProjectReference Include="../../src/PXA.Migration.DevExpressReport/PXA.Migration.DevExpressReport.csproj" />
    <ProjectReference Include="../../src/PXA.Migration.FastReport/PXA.Migration.FastReport.csproj" />
    <ProjectReference Include="../../src/PXA.Migration.JasperReports/PXA.Migration.JasperReports.csproj" />
    <ProjectReference Include="../../src/PXA.Migration.Rdl/PXA.Migration.Rdl.csproj" />
    <ProjectReference Include="../../src/PXA.Migration.Rpx/PXA.Migration.Rpx.csproj" />
    <ProjectReference Include="../../src/PXA.Migration.Stimulsoft/PXA.Migration.Stimulsoft.csproj" />
    <ProjectReference Include="../../src/PXA.Migration.Telerik/PXA.Migration.Telerik.csproj" />
  </ItemGroup>

</Project>
