<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../PXA.Migration.Abstractions/PXA.Migration.Abstractions.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.ActivePdf/PXA.Migration.Pdf.Code.ActivePdf.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.Apryse/PXA.Migration.Pdf.Code.Apryse.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.Aspose/PXA.Migration.Pdf.Code.Aspose.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.DevExpress/PXA.Migration.Pdf.Code.DevExpress.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.DsPdf/PXA.Migration.Pdf.Code.DsPdf.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.Foxit/PXA.Migration.Pdf.Code.Foxit.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.GemBox/PXA.Migration.Pdf.Code.GemBox.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.IronPdf/PXA.Migration.Pdf.Code.IronPdf.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.Leadtools/PXA.Migration.Pdf.Code.Leadtools.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.PdfKitNet/PXA.Migration.Pdf.Code.PdfKitNet.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.PdfTools/PXA.Migration.Pdf.Code.PdfTools.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.PdfToolsToolbox/PXA.Migration.Pdf.Code.PdfToolsToolbox.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.Spire/PXA.Migration.Pdf.Code.Spire.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.Syncfusion/PXA.Migration.Pdf.Code.Syncfusion.csproj" />
    <ProjectReference Include="../PXA.Migration.Pdf.Code.IText7/PXA.Migration.Pdf.Code.IText7.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
