<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../PXA.Migration.Report.Designer.ActiveReportsJs/PXA.Migration.Report.Designer.ActiveReportsJs.csproj" />
    <ProjectReference Include="../PXA.Migration.Report.Designer.DevExpress/PXA.Migration.Report.Designer.DevExpress.csproj" />
    <ProjectReference Include="../PXA.Migration.Report.Designer.FastReport/PXA.Migration.Report.Designer.FastReport.csproj" />
    <ProjectReference Include="../PXA.Migration.Report.Designer.JasperReports/PXA.Migration.Report.Designer.JasperReports.csproj" />
    <ProjectReference Include="../PXA.Migration.Report.Designer.Rdl/PXA.Migration.Report.Designer.Rdl.csproj" />
    <ProjectReference Include="../PXA.Migration.Report.Designer.Rpx/PXA.Migration.Report.Designer.Rpx.csproj" />
    <ProjectReference Include="../PXA.Migration.Report.Designer.Stimulsoft/PXA.Migration.Report.Designer.Stimulsoft.csproj" />
    <ProjectReference Include="../PXA.Migration.Report.Designer.Telerik/PXA.Migration.Report.Designer.Telerik.csproj" />
    <ProjectReference Include="../../../Core/PXA.Core/PXA.Core.csproj" />
    <ProjectReference Include="../../Common/PXA.Migration.Abstractions/PXA.Migration.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
