<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>

    <ProjectReference Include="../../Common/PXA.Migration.Abstractions/PXA.Migration.Abstractions.csproj" />
    <ProjectReference Include="../../../Core/PXA.Core/PXA.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
