export const siteLinks = {
  company: 'http://localhost:5173/',
  documentation: 'http://localhost:5174/',
  demo: 'http://localhost:5175/',
};

export const categories = [
  'All',
  'PDF Generator',
  'PDF Viewer',
  'Designer',
  'Report Migration',
  'Code Migration',
  'Spreadsheet',
  'Import/Export',
];

export const demos = [
  {
    id: 'booking-receipt',
    title: 'Invoice / Booking Receipt',
    category: 'PDF Generator',
    status: 'Ready',
    text: 'Generate and preview a business document from structured data and reusable layout primitives.',
    tags: ['PDF', 'Invoice', 'Preview'],
    input: 'Structured receipt data',
    output: 'Generated PDF preview',
    source: '/examples/booking-receipt/source.js',
    inputFile: '/examples/booking-receipt/input.json',
    outputFile: '/examples/booking-receipt/output.json',
    checklist: 'PXA.Demo',
    download: '/examples/booking-receipt/output.json',
    preview: {
      type: 'receipt',
      customer: 'Northwind Travel Desk',
      reference: 'BR-2026-0713',
      date: '2026-07-13',
      items: [
        { label: 'Conference room booking', quantity: 1, amount: '840.00' },
        { label: 'Catering package', quantity: 24, amount: '456.00' },
        { label: 'Service and setup', quantity: 1, amount: '180.00' },
      ],
      total: '1,476.00',
    },
  },
  {
    id: 'master-detail-report',
    title: 'Master-detail report',
    category: 'Report Migration',
    status: 'Preview',
    text: 'Inspect a migrated master-detail report structure with grouped sections and child rows.',
    tags: ['Reports', 'Bands', 'Data'],
    input: 'Report definition with nested data',
    output: 'Grouped report layout',
    source: 'checklists/Designer-Migration.md',
    checklist: 'Designer-Migration',
    download: 'master-detail-report.json',
    preview: {
      type: 'report',
      sections: ['Report header', 'Customer group', 'Order detail rows', 'Group footer'],
      note: 'Preview shows mapped report sections until a live renderer is connected.',
    },
  },
  {
    id: 'chart-report',
    title: 'Chart report',
    category: 'Designer',
    status: 'Preview',
    text: 'Review chart mapping expectations for report designers and generated document output.',
    tags: ['Charts', 'Designer', 'Reports'],
    input: 'Chart-capable report definition',
    output: 'Mapped chart placeholder and notes',
    source: 'checklists/UI-Advanced-Elements.md',
    checklist: 'UI-Advanced-Elements',
    download: 'chart-report.json',
    preview: {
      type: 'chart',
      series: [
        { label: 'Q1', value: 42 },
        { label: 'Q2', value: 64 },
        { label: 'Q3', value: 51 },
        { label: 'Q4', value: 78 },
      ],
    },
  },
  {
    id: 'rich-text-table-report',
    title: 'Rich text / table report',
    category: 'Report Migration',
    status: 'Planned',
    text: 'Track rich text, table layout, and mixed-content report migration fidelity.',
    tags: ['Rich text', 'Tables', 'Migration'],
    input: 'Report with mixed rich text and tables',
    output: 'Fidelity checklist status',
    source: 'checklists/Word-Element-Support-Matrix.md',
    checklist: 'Word-Element-Support-Matrix',
    download: 'rich-text-table-report.json',
    preview: {
      type: 'table',
      columns: ['Element', 'Mapping', 'Status'],
      rows: [
        ['Rich text', 'Inline spans', 'Planned'],
        ['Table', 'Rows and cells', 'Preview'],
        ['Mixed content', 'Composite blocks', 'Planned'],
      ],
    },
  },
  {
    id: 'pdf-viewer-annotations-forms',
    title: 'PDF viewer annotations/forms',
    category: 'PDF Viewer',
    status: 'Preview',
    text: 'Explore annotation and form workflows for browser-based PDF review scenarios.',
    tags: ['Viewer', 'Forms', 'Annotations'],
    input: 'PDF with forms and annotations',
    output: 'Interactive viewer workflow',
    source: 'checklists/PdfTools-WebViewer-Feature-Gaps.md',
    checklist: 'PdfTools-WebViewer-Feature-Gaps',
    download: 'viewer-annotations-forms.pdf',
    preview: {
      type: 'viewer',
      tools: ['Select', 'Highlight', 'Ink', 'Text note', 'Form fields'],
      note: 'Interactive viewer controls are represented here until the full PDF viewer runtime is embedded.',
    },
  },
  {
    id: 'spreadsheet-import-export',
    title: 'Spreadsheet import/export',
    category: 'Spreadsheet',
    status: 'Preview',
    text: 'Import workbook data, inspect mapped sheets, and prepare export-oriented workflows.',
    tags: ['Spreadsheet', 'Import', 'Export'],
    input: 'Workbook data',
    output: 'Mapped sheet and export flow',
    source: 'checklists/Spreadsheet-Import-Export.md',
    checklist: 'Spreadsheet-Import-Export',
    download: 'spreadsheet-import-export.xlsx',
    preview: {
      type: 'sheet',
      cells: [
        ['Region', 'Orders', 'Revenue'],
        ['North', '128', '42,900'],
        ['West', '96', '31,200'],
        ['South', '112', '38,450'],
      ],
    },
  },
  {
    id: 'provider-migration-examples',
    title: 'Provider migration examples',
    category: 'Code Migration',
    status: 'Preview',
    text: 'Compare migration outputs for known PDF and report providers across PXA migration tracks.',
    tags: ['Providers', 'Code', 'Reports'],
    input: 'Provider-specific code or report files',
    output: 'PXA migration result and diagnostics',
    source: 'checklists/Migration-Namespace-Taxonomy.md',
    checklist: 'Migration-Namespace-Taxonomy',
    download: 'provider-migration-examples.zip',
    preview: {
      type: 'migration',
      steps: ['Detect provider', 'Parse source', 'Map API surface', 'Emit PXA diagnostics'],
      note: 'Provider examples will become runnable once sample code packages are hosted.',
    },
  },
  {
    id: 'file-importer-flow',
    title: 'File importer flow',
    category: 'Import/Export',
    status: 'Planned',
    text: 'Bring files into normalized PXA data and document workflows.',
    tags: ['Importer', 'Files', 'Output'],
    input: 'PDF, Office, image, or document file',
    output: 'Normalized PXA import model',
    source: 'checklists/Importer-New-Featuers.md',
    checklist: 'Importer-New-Featuers',
    download: 'file-importer-flow.json',
    preview: {
      type: 'importer',
      steps: ['Upload file', 'Detect format', 'Normalize model', 'Preview output'],
      note: 'Upload support is held until safety limits are defined.',
    },
  },
];

export const statusNotes = [
  { title: 'Ready', text: 'The card can represent a runnable or immediately testable demo path.' },
  { title: 'Preview', text: 'The demo has mapped intent and source context, but needs deeper runtime integration.' },
  { title: 'Planned', text: 'The card documents roadmap intent and prevents empty or misleading demo pages.' },
];
